$env:TBOT_ALPHA_TREND_ON_TH  = "0.30"
$env:TBOT_ALPHA_TREND_CAP_TH = "0.15"
$env:TBOT_ALPHA_CHOP_CAP_TH  = "0.03"

Write-Host "WARMUP_ALPHA_ENV_ACTIVE"
Write-Host "TBOT_ALPHA_TREND_ON_TH=$env:TBOT_ALPHA_TREND_ON_TH"
Write-Host "TBOT_ALPHA_TREND_CAP_TH=$env:TBOT_ALPHA_TREND_CAP_TH"
Write-Host "TBOT_ALPHA_CHOP_CAP_TH=$env:TBOT_ALPHA_CHOP_CAP_TH"
