$env:TBOT_ALPHA_TREND_ON_TH  = "0.30"
$env:TBOT_ALPHA_TREND_CAP_TH = "0.15"
if ([string]::IsNullOrWhiteSpace($env:TBOT_ALPHA_CHOP_CAP_TH)) {
    throw "TBOT_ALPHA_CHOP_CAP_TH_MISSING_INHERITED_SOURCE"
}
if ([string]::IsNullOrWhiteSpace($env:TBOT_ALPHA_CHOP_CAP_TH_SOURCE)) {
    $env:TBOT_ALPHA_CHOP_CAP_TH_SOURCE = "INHERITED"
}

Write-Host "WARMUP_ALPHA_ENV_ACTIVE"
Write-Host "TBOT_ALPHA_TREND_ON_TH=$env:TBOT_ALPHA_TREND_ON_TH"
Write-Host "TBOT_ALPHA_TREND_CAP_TH=$env:TBOT_ALPHA_TREND_CAP_TH"
Write-Host "TBOT_ALPHA_CHOP_CAP_TH=$env:TBOT_ALPHA_CHOP_CAP_TH"

