# NOTE: BYPASS_NOT_INJECTED (no anchor match)
# OBS_ENV_INJECT_V1
$env:TBOT_RUNROOT = "C:\alpaca-bot\org_bot_runtime\shadow"
$env:TBOT_RUNTIME = $env:TBOT_RUNROOT
# SHADOW_RUNROOT_ARG_ENFORCE_V1
# SHADOW_ROOTARG_CANON_V1

# --- TBOT_SHADOW_SOFT_NEGEXP_ENV_V1 BEGIN ---
# Shadow-only: prevent "negative_expectancy" from hard-killing the day.
# Goal: keep the day representative for tuning, while keeping risk low + auditable.
# PT local time (24h). Until this time, hard-off is forbidden => soft mode instead.
# --- TBOT_SHADOW_SOFT_NEGEXP_ENV_V1 END ---

param(
  [string]$ProjectRoot="C:\alpaca-bot\org_bot",
  [string]$RunRoot="C:\alpaca-bot\org_bot_runtime\shadow",
  [string]$IsoDayOverride=""
)


# --- SESSION_GUARD_RTH_V1 (RTH only) ---
try {
  $nowLocal = Get-Date
  $tzET = [TimeZoneInfo]::FindSystemTimeZoneById("Eastern Standard Time")
  $nowET = [TimeZoneInfo]::ConvertTime($nowLocal, $tzET)

  # RTH window in ET: 09:30 - 16:00
  $startET = Get-Date -Date $nowET.Date.AddHours(9).AddMinutes(30)
  $endET   = Get-Date -Date $nowET.Date.AddHours(16).AddMinutes(0)

  if($nowET -lt $startET -or $nowET -gt $endET){
    $msg = ("[SESSION_GUARD] OUT_OF_SESSION: nowET={0} window=09:30-16:00 ET. Exiting 86." -f $nowET.ToString('yyyy-MM-dd HH:mm:ss'))
    if($env:TBOT_ALLOW_OUT_OF_SESSION -eq "1"){
      Write-Host "[SESSION_GUARD] BYPASSED via TBOT_ALLOW_OUT_OF_SESSION=1"
    } else {
      Write-Host $msg
      exit 86
    }
  }
} catch {
  # Fail-open: do not block run if timezone conversion fails
}
# --- SESSION_GUARD_RTH_V1 END ---


$ErrorActionPreference="Stop"
# ROOT_ALIAS_FIX_V3 (prevent Join-Path null; keep legacy aliases)
if([string]::IsNullOrWhiteSpace($ProjectRoot)){ $ProjectRoot="C:\alpaca-bot\org_bot" }
if([string]::IsNullOrWhiteSpace($RunRoot)){ $RunRoot="C:\alpaca-bot\org_bot_runtime\shadow" }
$ROOT=$ProjectRoot
$Root=$ProjectRoot

# PARAM_BLOCK_FIXED_V3 (auto; param moved to top)
if([string]::IsNullOrWhiteSpace($RunRoot)){ $RunRoot = "C:\alpaca-bot\org_bot_runtime\shadow" }

$env:TBOT_SHADOW_SOFT_NEGEXP = "1"
$env:TBOT_SHADOW_SOFT_NEGEXP_MIN_ACCEPTS = "120"
$env:TBOT_SHADOW_SOFT_NEGEXP_CAP_RATIO = "0.10"
$env:TBOT_SHADOW_SOFT_NEGEXP_COOLDOWN_SEC = "180"
$env:TBOT_SHADOW_SOFT_NEGEXP_SOFT_UNTIL_PT = "13:00"

# PARAM_BLOCK_FIXED_V2 (auto)
if([string]::IsNullOrWhiteSpace($RunRoot)){ $RunRoot = "C:\alpaca-bot\org_bot_runtime\shadow" }

# PARAM_BLOCK_FIXED_V1 (auto)
if([string]::IsNullOrWhiteSpace($RunRoot)){ $RunRoot = "C:\alpaca-bot\org_bot_runtime\shadow" }


# >>> TBOT_ENV_BEGIN (autogenerated)
$env:TBOT_ENABLE_S11_MVP     = "1"
$env:TBOT_S11_MIN_STRENGTH   = "0"
$env:TBOT_S11_MIN_CONF       = "0.55"
$env:TBOT_ALPHA_TREND_ON_TH  = "0"
$env:TBOT_ALPHA_TREND_CAP_TH = "0"
# <<< TBOT_ENV_END



function Log([string]$m){
  $ts=(Get-Date -Format "HH:mm:ss")
  Write-Host "[$ts] $m"
}


# ---- ATOMIC SINGLE INSTANCE (MUTEX) ----
$createdNew = $false
$mutexName  = "Global\TBOT_RUN_LIVE_SHADOW_CANON_V2"
$mutex      = [System.Threading.Mutex]::new($false, $mutexName, [ref]$createdNew)
if (-not $mutex.WaitOne(0)) {
  Write-Host "[LOCK] BLOCK: another RUN_LIVE_SHADOW_CANON_V2 instance is starting/running."
  exit 3
}
try {
# -------- paths (project-only) --------
$ROOT = $Root
$PY   = Join-Path $ROOT ".venv\Scripts\python.exe"
$OPS  = Join-Path $ROOT "logs\ops"
$LOCK = Join-Path $ROOT "logs\locks\RUN_SHADOW.lock"
$ENVPS1 = "C:\alpaca-bot\secrets\alpaca_env.ps1"

if(!(Test-Path $PY)){ throw "Missing PY: $PY" }
if(!(Test-Path $ENVPS1)){ throw "Missing secrets file: $ENVPS1" }

New-Item -ItemType Directory -Force -Path $OPS | Out-Null
New-Item -ItemType Directory -Force -Path (Split-Path $LOCK) | Out-Null

function Get-OrgBotRunning {
  # Detect by exact executable path AND commandline contains tbot.main
  Get-CimInstance Win32_Process -Filter "Name='python.exe'" -ErrorAction SilentlyContinue |
    Where-Object {
      $_.ExecutablePath -eq $PY -and
      ($_.CommandLine -like "*-m tbot.main*" -or $_.CommandLine -like "*tbot.main*")
    } |
    Select-Object ProcessId,CommandLine
}

function Kill-OrgBotRunning {
  $running = Get-OrgBotRunning
  foreach($r in $running){
    $pidToKill = [int]$r.ProcessId
    Log ("KILL_PID=" + $pidToKill)
    Stop-Process -Id $pidToKill -Force -ErrorAction SilentlyContinue
  }
}

# -------- STRICT SINGLE INSTANCE --------
$running = @(Get-OrgBotRunning)
if($running.Count -gt 0 -and $Force -ne 1){
  Log "BLOCK: org_bot bot already running (use -Force 1 only if you intend to replace it)."
  $running | Format-Table -Auto | Out-String | Write-Host
  exit 3
}

if($Force -eq 1 -and $running.Count -gt 0){
  Log "FORCE=1: replacing existing run..."
  Kill-OrgBotRunning
  Start-Sleep 2
  if(Test-Path $LOCK){
    Remove-Item $LOCK -Force -ErrorAction SilentlyContinue
    Log "LOCK_CLEARED_FORCE"
  }
}

# -------- lock hygiene (stale lock only) --------
if(Test-Path $LOCK){
  # If lock exists but nothing running -> stale
  $still = @(Get-OrgBotRunning)
  if($still.Count -eq 0){
    Remove-Item $LOCK -Force -ErrorAction SilentlyContinue
    Log "STALE_LOCK_CLEARED"
  } else {
    # should have been blocked above, but keep safe
    Log "BLOCK: lock exists and bot running."
    exit 3
  }
}

# -------- env + start --------
Set-Location $ROOT
$env:PYTHONPATH = $ROOT

. $ENVPS1

# Shadow toggles
$env:TBOT_MVP="1"
$env:TBOT_S01_ENABLE="1"
$env:TBOT_S11_ENABLE="1"

# pricing knobs
$env:TBOT_SHADOW_PRICE_MODE="last"
$env:TBOT_SHADOW_RR="2.0"
$env:TBOT_SHADOW_STOP_PCT="0.003"

$ts2=(Get-Date -Format "yyyyMMdd_HHmmss")
$OUT=Join-Path $OPS ("LIVE_OUT_{0}.txt" -f $ts2)
$ERR=Join-Path $OPS ("LIVE_ERR_{0}.txt" -f $ts2)

Log "ROOT=$ROOT"
Log "PY=$PY"
Log "OUT=$OUT"
Log "ERR=$ERR"
Log "START LIVE shadow..."

Start-Process -FilePath $PY -ArgumentList @(
  "-u","-m","tbot.main",
  "--run","--iters","999999","--sleep","0.25",
  "--shadow",
  "--gate_min_rr","1.0",
  "--gate_min_conf","0.0",
  "--gate_cooldown_sec","45",
  "--gate_max_plans_per_day","150",
  "--gate_max_risk_usd","500"
) -WorkingDirectory $ROOT -RedirectStandardOutput $OUT -RedirectStandardError $ERR | Out-Null

Start-Sleep -Seconds 2

# Find newest venv python (project-only)
$liveProc = Get-Process python -ErrorAction SilentlyContinue |
  Where-Object { $_.Path -eq $PY } |
  Sort-Object StartTime |
  Select-Object -Last 1

if(!$liveProc){
  Log "FAIL_START: no python process found after Start-Process."
  exit 2
}

$livePid = $liveProc.Id
Log ("LIVE_PID=" + $livePid)

# Write lock
$lockLines = @(
  ("ts={0} user={1} host={2} root={3}" -f (Get-Date -Format "s"), $env:USERNAME, $env:COMPUTERNAME, $ROOT),
  ("pid={0}" -f $livePid),
  ("out={0}" -f $OUT),
  ("err={0}" -f $ERR),
  ("strict=1"),
  ("force={0}" -f $Force)
)
$lockLines | Set-Content -Encoding UTF8 -LiteralPath $LOCK

# Fail-fast healthcheck (process alive + logs exist)
Start-Sleep -Seconds 2
$alive = Get-Process -Id $livePid -ErrorAction SilentlyContinue
if(!$alive){
  Log "FAIL_START: process exited early."
  if(Test-Path $LOCK){ Remove-Item $LOCK -Force -ErrorAction SilentlyContinue; Log "LOCK_CLEARED_ON_FAIL" }
  Log "=== ERR tail (120) ==="
  if(Test-Path $ERR){ Get-Content -Tail 120 $ERR | ForEach-Object { $_ } }
  Log "=== OUT tail (120) ==="
  if(Test-Path $OUT){ Get-Content -Tail 120 $OUT | ForEach-Object { $_ } }
  exit 2
}

Log "HEALTHCHECK_OK"
Log "TIP: Tail logs with:"
Log ("  Get-Content -Wait -Tail 80 `"{0}`"" -f $OUT)
Log ("  Get-Content -Wait -Tail 80 `"{0}`"" -f $ERR)
}
finally {
  try { $mutex.ReleaseMutex() } catch {}
  try { $mutex.Dispose() } catch {}
}
















